### ISSUE TITLE
Standalone Flycast mapping?

### ISSUE THREAD

**Issue by retropieuser** [lowlevel-1989/dbar4gun#1]
Hi there,

This works really well in lr-fbneo and other retroarch cores but I notice it doesn't allow me to map properly in flycast. It does in lr-flycast given it's a retroarch core, but I like having standalone flycast as an option so I can use higher internal resolutions on Naomi games like Confidential Mission & HOTD2.

I find it only lets me Map B, 1 & 2 as Left, Middle and Right mouse buttons, it seems A gets mapped to a scroll key or holding A down lets me scroll in the menu but does nothing when trying to map it to a Dreamcast/arcade button (the IR still functions as the mouse movement)

**Comment by lowlevel-1989** [comment]
> Hi there,
> 
> This works really well in lr-fbneo and other retroarch cores but I notice it doesn't allow me to map properly in flycast. It does in lr-flycast given it's a retroarch core, but I like having standalone flycast as an option so I can use higher internal resolutions on Naomi games like Confidential Mission & HOTD2.
> 
> I find it only lets me Map B, 1 & 2 as Left, Middle and Right mouse buttons, it seems A gets mapped to a scroll key or holding A down lets me scroll in the menu but does nothing when trying to map it to a Dreamcast/arcade button (the IR still functions as the mouse movement)

Correct, for these cases you need a manual configuration, which is documented in this link: [Configuration Manual for Specific Core Games](https://github.com/lowlevel-1989/dbar4gun/tree/master/retroarch)

The House of the Dead 2: [https://github.com/lowlevel-1989/dbar4gun/tree/master/retroarch/dreamcast/House%20of%20the%20Dead%202](https://github.com/lowlevel-1989/dbar4gun/tree/master/retroarch/dreamcast/House%20of%20the%20Dead%202)

I can perform the tests you mentioned over the weekend and I can give you more accurate feedback.

**Comment by lowlevel-1989** [comment]
Are you using an rpi version or a pc with linux?

**Comment by retropieuser** [comment]
Am using a rpi5, so there's no way to add manual configuration for standalone non retroarch programs?

**Comment by lowlevel-1989** [comment]
@retropieuser Tell me if you have manually compiled the emulator and in what version, to perform the same tests and work on support.

**Comment by retropieuser** [comment]
pkg_origin="source"
pkg_date="2024-10-25T22:38:35+01:00"
pkg_repo_type="git"
pkg_repo_url="https://github.com/flyinghead/flycast.git"
pkg_repo_branch="master"
pkg_repo_commit="e221f6fed2964d83c871384fc19a06541ce76aba"
pkg_repo_date="2024-10-25T08:10:41+02:00"
pkg_repo_extra=""

This is the version

**Comment by lowlevel-1989** [comment]
> pkg_origin="source" pkg_date="2024-10-25T22:38:35+01:00" pkg_repo_type="git" pkg_repo_url="https://github.com/flyinghead/flycast.git" pkg_repo_branch="master" pkg_repo_commit="e221f6fed2964d83c871384fc19a06541ce76aba" pkg_repo_date="2024-10-25T08:10:41+02:00" pkg_repo_extra=""
> 
> This is the version

I'm already working on the support, thank you very much, I hope to have a first version by this weekend

**Comment by lowlevel-1989** [comment]
> pkg_origin="source" pkg_date="2024-10-25T22:38:35+01:00" pkg_repo_type="git" pkg_repo_url="https://github.com/flyinghead/flycast.git" pkg_repo_branch="master" pkg_repo_commit="e221f6fed2964d83c871384fc19a06541ce76aba" pkg_repo_date="2024-10-25T08:10:41+02:00" pkg_repo_extra=""
> 
> This is the version

Hi @retropieuser, dbar4gun 0.17.0 is your version, I have already released it

[CHANGELOG](https://github.com/lowlevel-1989/dbar4gun/blob/master/CHANGELOG)
